[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nakama = "HSbykjMFKgX4HhPBdBzDwMBrRVugatiCXrQEC1J9Ccfm"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
